# docker-compose.override.yml
version: "3.8"

services:
  postgres:
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      target: builder
    image: riotjs-nginx-example-backend-dev:master
    environment:
      DEBUG: "true"
      SSL_CERT_PATH: /etc/ssl/certs/cert.pem
      SSL_KEY_PATH: /etc/ssl/private/privkey.pem
    ports:
      - "5000:5000"
    volumes:
      - ${PWD}/backend:/app/
      - ${HOME}/.ssl/certs/localhost.pem:/etc/ssl/certs/cert.pem
      - ${HOME}/.ssl/private/localhost.pem:/etc/ssl/private/privkey.pem

  frontend:
    build:
      context: ./frontend
      target: dev-server
    container_name: frontend
    hostname: frontend
    image: riotjs-nginx-example-frontend-dev:master
    command: npm run start
    networks:
      - riotjs-nginx-example-network
    expose:
      - "3000"
    ports:
      - "3000:3000"
    restart: on-failure
    volumes:
      - ${PWD}/frontend/src:/var/www/app/src

  nginx:
    command: sh -c "
      wait-for.sh adminer:8080 &&
      wait-for.sh backend:5000 &&
      wait-for.sh frontend:3000 &&
      nginx -g 'daemon off;'"
    depends_on:
      - adminer
      - backend
      - frontend
    volumes:
      - ${PWD}/nginx/dev.nginx.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/scripts/wait-for.sh:/bin/wait-for.sh
