# docker-compose.yml
version: "3.8"

services:
  nginx:
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    container_name: nginx
    hostname: nginx
    image: riotjs-nginx-example-frontend:master
    networks:
      - riotjs-nginx-example-network
    ports:
      - "80:80"
      - "443:443"
    restart: on-failure
    volumes:
      - ${PWD}/nginx/prod.nginx.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}/nginx/extras.conf:/etc/nginx/extras.conf
      - ${PWD}/nginx/cache_expiration.conf:/etc/nginx/cache_expiration.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot

  certbot:
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    container_name: certbot
    image: certbot/certbot
    networks:
      - riotjs-nginx-example-network
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot

networks:
  riotjs-nginx-example-network:
    driver: bridge

volumes:
  certbot-etc:
    name: "certbot-etc"
  certbot-www:
    name: "certbot-www"
