# docker-compose.yml
version: "3.8"

services:
  nginx:
    container_name: nginx
    hostname: nginx
    image: riotjs-nginx-example-frontend:master
    networks:
      - riotjs-nginx-example-network
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ${PWD}/reverseproxy/prod.nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  riotjs-nginx-example-network:
    driver: bridge
